name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  ubuntu-tests:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: run tests
        run: node tests

  windows-tests:

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v2

      - name: install dependencies
        run: npm install

      - name: run tests
        run: node tests